import * as struct from '../../structs';

/** Client state record for NFS v4 client registration. */
export class ClientRecord {
  constructor(
    /**
     * Client verifier - used to detect client reboots.
     * If client sends SETCLIENTID with same clientIdString but different verifier,
     * it indicates the client rebooted and old state should be discarded.
     */
    public readonly verifier: Uint8Array,
    /**
     * Client identifier string - globally unique client identity.
     * Typically contains hostname, boot time, or other unique data.
     * Used to find existing client records across SETCLIENTID calls.
     */
    public readonly clientIdString: Uint8Array,
    /**
     * Server-assigned client ID - short numeric handle.
     * Returned to client and used in subsequent operations (OPEN, LOCK, etc.)
     * to identify this client. More efficient than sending full clientIdString.
     */
    public readonly clientid: bigint,
    /**
     * Callback information - RPC program number and network address.
     * Used by server to initiate callbacks to client (e.g., for delegation recalls).
     * Server opens new TCP connection to client using this address when needed.
     */
    public readonly callback: struct.Nfsv4CbClient,
    /**
     * Callback identifier - client-provided value.
     * Sent by server in callback RPCs to help client distinguish which
     * server is calling back (useful if client talks to multiple servers).
     */
    public readonly callbackIdent: number,
    /**
     * SETCLIENTID confirmation verifier - random 8-byte token.
     * Generated by server, returned to client, must be echoed back in
     * SETCLIENTID_CONFIRM to prove client received the SETCLIENTID response.
     * Prevents race conditions and stale client ID reuse.
     */
    public readonly setclientidConfirm: Uint8Array,
    /**
     * Confirmed status - whether SETCLIENTID_CONFIRM was called.
     * Unconfirmed records are temporary; only confirmed records can be
     * used for stateful operations (OPEN, LOCK, delegations).
     */
    public readonly confirmed: boolean,
  ) {}
}
